name: "Inventario Casa"
version: "2.2.1"
slug: "inventario_casa"
description: "Inventario domestico modulare per oggetti, posizioni, foto e tipologie personalizzabili"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_icon: "mdi:archive-search"
panel_title: "Inventario Casa"
panel_admin: false
backup: cold
map:
  - type: media
    read_only: false
options: {}
schema: {}
